---
kind: pipeline
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: 233704588990.dkr.ecr.ap-northeast-1.amazonaws.com/ci/debian:stretch
  commands:
  - cp -rf debian/pin-priority /etc/apt/preferences.d/backports
  - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
  - apt-get update && apt-get install -y debhelper libc-ares-dev libssl-dev libwrap0-dev python-all python3-all uthash-dev xsltproc docbook-xsl libcunit1-dev libwebsockets-dev pkg-config uuid-dev libsystemd-dev
  - make test
  when:
    event:
      include:
      - pull_request

- name: build-deb
  image: 233704588990.dkr.ecr.ap-northeast-1.amazonaws.com/ci/debian:stretch
  commands:
  - cp -rf debian/pin-priority /etc/apt/preferences.d/backports
  - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
  - apt-get update && apt-get install -y debhelper libc-ares-dev libssl-dev libwrap0-dev python-all python3-all uthash-dev xsltproc docbook-xsl libcunit1-dev libwebsockets-dev pkg-config uuid-dev libsystemd-dev
  - make dist
  - cd $(find ./ -name "mosquitto-*.*.*" -type d)
  - dpkg-buildpackage -us -uc
  when:
    event:
      exclude:
      - promote
      - tag

- name: upload
  image: 233704588990.dkr.ecr.ap-northeast-1.amazonaws.com/ci/awscli:latest
  commands:
  - mkdir result
  - cp ./dist/*.deb ./dist/*.dsc ./dist/*.changes result
  - aws s3 cp ./result/ $${S3_TARGET} --recursive --exclude "*" --include "*.deb" --include "*.dsc" --include "*.changes"
  environment:
    S3_TARGET: s3://moxaics/v3/edge/builds/${DRONE_REPO_NAME}/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}
  when:
    event:
      exclude:
      - promote
      - tag

---
kind: pipeline
name: build-armhf

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: 233704588990.dkr.ecr.ap-northeast-1.amazonaws.com/ci/debian:armhf-stretch
  commands:
  - cp -rf debian/pin-priority /etc/apt/preferences.d/backports
  - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
  - apt-get update && apt-get install -y debhelper libc-ares-dev libssl-dev libwrap0-dev python-all python3-all uthash-dev xsltproc docbook-xsl libcunit1-dev libwebsockets-dev pkg-config uuid-dev libsystemd-dev
  - make test
  when:
    event:
      include:
      - pull_request

- name: build-deb
  image: 233704588990.dkr.ecr.ap-northeast-1.amazonaws.com/ci/debian:armhf-stretch
  commands:
  - cp -rf debian/pin-priority /etc/apt/preferences.d/backports
  - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
  - apt-get update && apt-get install -y debhelper libc-ares-dev libssl-dev libwrap0-dev python-all python3-all uthash-dev xsltproc docbook-xsl libcunit1-dev libwebsockets-dev pkg-config uuid-dev libsystemd-dev
  - make dist
  - cd $(find ./ -name "mosquitto-*.*.*" -type d)
  - dpkg-buildpackage -us -uc
  when:
    event:
      exclude:
      - promote
      - tag

- name: upload
  image: 233704588990.dkr.ecr.ap-northeast-1.amazonaws.com/ci/awscli:latest
  commands:
  - mkdir result
  - cp ./dist/*.deb ./dist/*.dsc ./dist/*.changes result
  - aws s3 cp ./result/ $${S3_TARGET} --recursive --exclude "*" --include "*.deb" --include "*.dsc" --include "*.changes"
  environment:
    S3_TARGET: s3://moxaics/v3/edge/builds/${DRONE_REPO_NAME}/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}
  when:
    event:
      exclude:
      - promote
      - tag

---
kind: pipeline
name: publish

platform:
  os: linux
  arch: amd64

steps:
- name: upload-to-stable
  image: 233704588990.dkr.ecr.ap-northeast-1.amazonaws.com/ci/awscli:latest
  commands:
  - aws s3 cp $${S3_SOURCE} $${S3_TARGET} --recursive
  environment:
    S3_SOURCE: s3://moxaics/v3/edge/builds/${DRONE_REPO_NAME}/${DRONE_BRANCH}/${CI_PARENT_BUILD_NUMBER}
    S3_TARGET: s3://moxaics/v3/edge/stable/${DRONE_REPO_NAME}/${CI_PARENT_BUILD_NUMBER}
  when:
    event:
    - promote

...
